### ISSUE TITLE
TimeGrid Document

### ISSUE THREAD

**Issue by rajashekhar-hr** [rokudev/SceneGraphDeveloperExtensions#13]
I don't see any document for TimeGrid Component. It will be helpful if you could create a document for TimeGrid

**Comment by RajashekharHR** [comment]
any update?

**Comment by jduval23** [comment]
Hi,

We are currently working on finalizing the release of our TimeGrid documentation. I would expect the release to happen sometime in October.

Roku Developer Relations Team

**Comment by JorgeMendozaG** [comment]
Hi!, Is the documentation available? 
Thanks!

**Comment by jduval23** [comment]
Hi,

We're still waiting on finalizing the release of this documentation. The ETA is now in January. Thanks for your patience.

Roku Developer Relations Team

**Comment by rajashekhar-hr** [comment]
Any update?

**Comment by jduval23** [comment]
Actually, we released the TimeGrid yesterday. You can check it out here: 
https://developer.roku.com/docs/references/scenegraph/list-and-grid-nodes/timegrid.md

**Comment by JorgeMendozaG** [comment]
Thanks!, There is no information about the permission needed, we are getting a warning:

>  "TimeGrid" usage detected. Usage of this component is restricted. If you don’t have the corresponding permission, it will be flagged during channel certification

What does flagged mean?

**Comment by jduval23** [comment]
Where are you seeing this message? Please advise and we'll resolve this.

**Comment by JorgeMendozaG** [comment]
In the Static Analysis, after upload the pkg on the dashboard.
