### ISSUE TITLE
How to create a Menu 

### ISSUE THREAD

**Issue by RajashekharHR** [rokudev/SceneGraphDeveloperExtensions#14]
I'm using the framework in one of the application. The app has a Menu feature init. Not sure how to integrate with the other screen. It would be helpful if you can provide a sample app

**Comment by RokuChris** [comment]
There is no standalone menu component in SGDEX. Some developers get creative with GridView or CategoryListView to build menus. You can also build your own view and use it within an SGDEX channel, there's a sample of that here: https://github.com/rokudev/SceneGraphDeveloperExtensions/tree/master/samples/8_Custom%2BScreen
