### ISSUE TITLE
TimeGridView : Required to Display Previous Program

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#18]
Here, I view TimeGridView Component. At the application launch time, only display the next program. But, I require the previous program also. so please, add that type of feature.

**Comment by RokuChris** [comment]
You can do this by setting the _contentStartTime_ field on your TimeGridView. For instance, this would allow the user to scroll 6h into the past...

```
    view = CreateObject("roSGNode", "TimeGridView")
    view.contentStartTime = CreateObject("roDateTime").AsSeconds() - (3600 *6)

```

**Comment by chaklasiyanikunj** [comment]
Ok, Thank you for your reply. I will try.

**Comment by chaklasiyanikunj** [comment]
Hello, @RokuChris, It's Working fine for displaying users to scroll 6h or any number of the day into the past. But It's working only 30min program or 1H program. If the user found any random program like 23 min or 12 min it displays fine But some It adds a blank rectangle between two programs. any separate logic for blank rectangle adds between two programs? I start to play past 6h. and assume the current time is 12:00. So content starts to display past 6h and the start time is 6:00. But I'm not clear. I load content. Some time It starts to display 6:00 or sometimes It 6:30. Is there any way for playstart to give a content start time.

**Comment by RokuChris** [comment]
This may be a problem with the underlying SceneGraph component. I can open a ticket to have it investigated internally. For now, our recommendation is that program boundaries always be on half-hour marks and that durations be in increments of 30m.

**Comment by chaklasiyanikunj** [comment]
Ok. Thank you. For any update regarding this please inform me. Second thing is I start to play past 6h. and assume the current time is 12:00. So content starts to display past 6h and the start time is 6:00. But I'm not clear. I load content. Some time It starts to display 6:00 or sometimes It 6:30. Is there any way for playstart to give a content start time.
