### ISSUE TITLE
TimeGridView : Fetch Current Program

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#20]
In TimeGridView Component, Left-side Displays ChannelName and Right-side Displays EPG Program Name. It's very cool. But I tried to Display only the Current Playing Program For All Playing Channel. and Its Update Every time if Time Should Change. Is it Possible or any way to Implement that Scenario.

**Comment by RokuChris** [comment]
SGDEX does not explicitly support a "now playing" style in TimeGridView. This is someting we are considering, but I don't know when it would be released.

You can accomplish something similar today by populating the grid with one item per row.

There is also a field in the underlying TimeGrid node called _nowNextMode_ that you could experiment with. **This is not officially supported in SGDEX, so use at your own risk.** You can enable it like this.

```
    view = CreateObject("roSGNode", "TimeGridView")
    view.FindNode("timegrid").nowNextMode = true
```

**Comment by chaklasiyanikunj** [comment]
Ok, Thank you for your Reply. Update TimeGridView every 30 sec right. so, I can not fetch the index in the program. Its move All Program After 30 min right. I think you start a display program adjust using duration. I tried to fetch index using season_number So every 30 min Season_number should be changed. All season_number is unique. So, I Find also Program name using a season_number right?

**Comment by RokuChris** [comment]
TimeGridView doesn't directly use _season_number_ for anything. The position of items on the grid is based on their _playStart_ value. 

How you manipulate data within your ContentHandlers is up to you. In mot cases, _season_number_ is not unique and I would recommend using a GUID to identify things. But if _season_number_ works in your case, that's fine. We designed SGDEX with flexibility in mind, knowing that no two APIs work quite the same.

I'm not sure this helps, but you can observe the _rowItemSelected_ field on TimeGridVIew to get the row and item indices when the user selects an item.

```
        <!--
            Updated when user selects a program from the TimeGrid
            Value is an array of indexes represents [channelIndex, programIndex]
            updated simultaneously with channelSelected and programSelected
        -->
        <field id="rowItemSelected" type="array" alwaysNotify="true" />
```

**Comment by chaklasiyanikunj** [comment]
Thank you, For Your Great Reply. It's very helpful to me. Here fire one thread Right?. Here Thread Is Fire After 30 min? or It's Check every time ProgramData.
