### ISSUE TITLE
 Is It Possible to open another View inside a View? 

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#23]
I tried to open a another view inside a View. I'm in a TimeGridView and tried to open a Search View inside a TimeGridView. I tried with append child But It's Doesn't Help. I tried in onkeyevent() inside a TimeGridView to open a SearchView. I tried to press the options button to set all focus in SearchView and Inside a SearchView press back to open again TimeGridView and all Focus Set to TimeGridView. Is it Possible? Thanks. My onkeyevent code if condition like below
```
if key = "options" then
  ?"open Search scene"
    m.view.visible = false
    searchView = CreateObject("roSGNode", "SearchView")
    searchView.hintText = "Enter search term"

    ' query field will be changed each time user has typed something
    searchView.ObserveFieldScoped("query", "OnSearchQuery")
    searchView.ObserveFieldScoped("rowItemSelected", "OnSearchItemSelected")
    m.top.appendChild(searchView)
    m.top.visible = true
end if
```

**Comment by RokuChris** [comment]
You cannot open a view inside or as a child of another view. SGDEX uses a stack paradigm. To push a new view onto the stack, use the ComponentController's `show()` function. 

```
  view = CreateObject("roSGNode", "SearchView")
  m.top.ComponentController.callFunc("show", { view: view })
```

There is a more detailed discussion of this here: https://github.com/rokudev/SceneGraphDeveloperExtensions/blob/master/documentation/3-ViewStack_Guide.md

**Comment by chaklasiyanikunj** [comment]
ok thank you for your great reply
