### ISSUE TITLE
Is TimeGrid independent component?

### ISSUE THREAD

**Issue by rajashekhar-hr** [rokudev/SceneGraphDeveloperExtensions#26]
Hi guys,

The app is not built using **SceneGraphDeveloperExtension**. Is it possible to use just TimeGrid component because I don't want to re-write the whole app just to use **TimeGrid**

**Comment by RokuChris** [comment]
Yes, TimeGrid is a RSG component. It's documented here: https://developer.roku.com/docs/references/scenegraph/list-and-grid-nodes/timegrid.md

You don't necessarily have to rewrite a channel to take advantage of SGDEX. if the buit in SGDEX views don't meet your needs, you can use the SGDEX ComponentController to manage a stack of your own custom screens. Or you can mix and match SGDEX views with custom views. There's a simple example of that here: https://github.com/rokudev/SceneGraphDeveloperExtensions/tree/master/samples/8_Custom%2BScreen

**Comment by rajashekhar-hr** [comment]
great! Built a Real world TimeGrid. Its looking awesome. 
**Thanks for the wonderful component** 
💯 👍
