### ISSUE TITLE
Can not run app on device first lesson

### ISSUE THREAD

**Issue by UladzKha** [rokudev/SceneGraphDeveloperExtensions#28]
Hi i was following your tutorial and when i try to deploy app on roku i get error 

> Found 1 parse error in XML file MainScene.xml
--- Line 4: XML syntax error found ---> junk after document element
02-06 14:21:13.990 [scrpt.parse.mkup.time] Parsed markup dev 'Mirek Channel' in 2 milliseconds

please help me to change this file 
`<?xml version="1.0" encoding="UTF-8"?>
    <component name="MainScene" extends="BaseScene" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://devtools.web.roku.com/schema/RokuSceneGraph.xsd">
    
    <script type="text/brightscript" uri="pkg:/components/MainScene.brs"/>
</component>`

**Comment by RokuChris** [comment]
The sample is working for me. I tried it using the version of MainScene.xml in the repository as well as the version you pasted here. Both compiled successfully. If you can share the firmware version and model of the device you're using, that might help us reproduce it.

Did you change anything else about the channel before side loading it? I noticed that the channel name is different in your case than when using the sample as-is.

`02-06 14:21:13.990 [scrpt.parse.mkup.time] Parsed markup dev 'Mirek Channel' in 2 milliseconds
`

When I run the sample from the repository, that line looks like this.

`02-06 16:11:36.635 [scrpt.parse.mkup.time] Parsed markup dev 'SGDEX Sample Hello World' in 96 milliseconds
`

**Comment by knastordin** [comment]
It works fine, I can't recall but I just copied additional .brs from the source files to my project and it helped
