### ISSUE TITLE
Which point EPG data fill in TimeGrid?

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#29]
I tried to understand the whole example. But I don't know exactly which point EPG Data filled in TimeGrid.
In ContentManager.brs file many functions. But which function is used to fill data. I'm not sure But It's OnRootContentLoaded(). I required to sort channel id wise and display. So I don't find any method for sorting a node.  Is there any way of sorting an EPG grid?

**Comment by RokuChris** [comment]
There is no functionality built into SGDEX for sorting content. That's something you would need to do yourself in your ContentHandler. TimeGridView will display its rows in whatever order you arrange them. Each row is represented by a child of the root ContentNode as described here: https://developer.roku.com/docs/references/scenegraph/list-and-grid-nodes/timegrid.md#content

**Comment by chaklasiyanikunj** [comment]
Thank you @RokuChris  For your quick response. Ok I got it. From my side It's very confusing to find which place to EPG Data filled in TimeGrid. Please let me know.

**Comment by RokuChris** [comment]
All SGDEX views are populated in their respective ContentHandlers. There's a description of that here: https://github.com/rokudev/SceneGraphDeveloperExtensions/blob/master/documentation/2-Contenthandlers_Guide.md

Tthe TimeGridView sample channel uses a row-by-row loading model, so it has two ContentHandlers. CHRoot populates the rows and CHRow populates the items for each row.

**Comment by chaklasiyanikunj** [comment]
Hello, I read the documentation. But I only single time to call API. I required to dynamic sort It means I set one Button Above in time grid I press this button it sort id wise and again press button it sort name wise. I found data load in time grid in content manager file OnRootContentLoaded() use `m.view.content = m.top.content`. All nodes are set here to as time grid view content.  and doPrioritySort() Is use for data arrangement?

**Comment by RokuChris** [comment]
We do not reccomend changing the ContentManager or anything else in the SGDEX folder. If you aren't using SGDEX as is, it becomes difficult for us to help you. At that point you are really developing a RSG channel and not an SGDEX channel.

The recommended way to update the data on any SGDEX view is to place a new _handlerConfig*_ field on its root ContentNode. This will force the ContentManager to run again.

**Comment by chaklasiyanikunj** [comment]
Thank you, For your great reply. Now I clearly understand.

**Comment by chaklasiyanikunj** [comment]
Hello, @RokuChris Thank you. I was applied to your idea. it works well. I still need some help from you. I read this documentation https://sdkdocs-archive.roku.com/Using-ViewStack_5443630.html. Here, I see add a new view or close view. like below.
```
sub onShowLoginPage()
    banner = CreateObject("roSGNode", "MyBannerView")
    banner.observeField("wasClosed", "onBannerClosed")
    m.timer = CreateObject("roSGNode", "Timer")
    'if user doesn't perform anything close the view
    m.timer.duration = 20
    m.timer.control = "start"
    m.timer.observeField("fire", "closeBanner")
    'This will add your view to stack
    m.top.ComponentController.callFunc("show", {
        view: banner
    })
    m.banner = banner
end sub

sub closeBanner()
    m.banner.close = true
end sub
```
I study the Viewstack component in SGDEX Sample. Here I found 5 components.
```
    m.addView = addView 
    m.closeView = closeView
    m.closeToView = closeToView
    m.replaceCurrentView = replaceCurrentView
    m.syncOutProperties = syncOutProperties
    m.saveState = saveState
```
I am not aware of the replaceCurrentView. you know how I can use this in view.

**Comment by RokuChris** [comment]
Those fields are used internally by SGDEX to manage the stack. They are not meant to be used directly by developers.

**Comment by chaklasiyanikunj** [comment]
Ok, thank you for the great information.
