### ISSUE TITLE
Changing the program color is possible

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#30]
Here 5 channel programs and 4 channel light color and 5th channel Dark. I required all channels in a Dark color. I read the documentation I find the programTitleColor field for change program color. Here no luck. I think A rectangle is above that field. I'm not sure about this thing. Is it correct? which rectangle used 5th field. So, I can change size of that rectangle. 

![image](https://user-images.githubusercontent.com/39697799/76739200-e51ca500-6791-11ea-9173-f28c02680594.png)

**Comment by RokuChris** [comment]
That shadow is not part of SGDEX. That is rendered as part of the underlying SceneGraph TimeGrid component and controlled by the _overlayBitmapUri_ field. More on that here: https://developer.roku.com/docs/references/scenegraph/list-and-grid-nodes/timegrid.md#general-timegrid-settings

SGDEX does not currently provide a way for developers to change that field, but I can open an internal feature request to add that ability.

**Comment by chaklasiyanikunj** [comment]
ok thank you for your great reply
