### ISSUE TITLE
Future Time Screen instead of Past Time Screen

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#31]
Roku provides a Past Time Screen that's a cool and unique concept. But Some User is required Future Time Screen instead of Past Time Screen. TimeGrid Provide Future Time Screen? or It will available on the next update?

**Comment by RokuChris** [comment]
The SceneGraph TimeGrid component does not currently support this and I am not aware of any plan to add it. I can open an internal feature request for it.

There are various color related fields on the TimeGrid component that you might be able to use to do something approximating what you want, but those are not exposed through the current SGDEX TimeGridView.

**Comment by chaklasiyanikunj** [comment]
Thank you, Your answer always helps me.
