### ISSUE TITLE
Programs up-down continuous should not Required

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#32]
Is It possible to stop Scrolling 1-20 channels infinitely loop? I focus on the 1st channel program and press up key It focuses on transfer in the last channel. It displays in a loop with the Continued process. I tried with a fetch index of that program using programFocused() and handled the up/down key in a time grid view. But no luck. Is there any way to do this?

**Comment by RokuChris** [comment]
There is no way to disable vertical wrapping. This is a limitation of the underlying SceneGraph TimeGrid component.

**Comment by chaklasiyanikunj** [comment]
Thank you for your Great Reply.
