### ISSUE TITLE
Don't understand jump to live works.

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#33]
Jump to Live works in reload key. That's cool. But I don't understand how it works? I tried to find it in code. Also, read the documentation. But no luck. Jump to live functionality used for any specific field? or that is a built-in functionality?

**Comment by RokuChris** [comment]
This is not an SGDEX feature. It is part of the SceneGraph TimeGrid component.

**Comment by chaklasiyanikunj** [comment]
ok, Thank you.

**Comment by chaklasiyanikunj** [comment]
At Time Of EPG Launch, I try to Live pin Display on the Center of the screen. I used both field (nowBarOffset, minimumNowBarOffset). But no luck. Is there any way to It Displaying on Center.
