### ISSUE TITLE
Now Bar Display on a Center(In the middle of the screen)

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#35]
At Time Of EPG Launch, I try to Live pin(Now Bar) Display on the Center of the screen. I used both field (nowBarOffset, minimumNowBarOffset). But, I think I required to change both position TimeBar and Now Bar. But no luck. Is there any way or feature available to It Displaying on Center.

**Comment by RokuChris** [comment]
Fields like _nowBarOffset_ and _minimumNowBarOffset_ are not exposed through SGDEX and changing them when using TimeGridView is not recommended. 

If you want to use the RSG TimeGrid component separate from the SGDEX TimeGridView, the developer forum is a good source of information. https://community.roku.com/t5/Roku-Developer-Program/bd-p/roku-developer-program

**Comment by chaklasiyanikunj** [comment]
Thank you for your great response.
