### ISSUE TITLE
How Focus Works with ButtonBar.

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#36]
I test the Button Bar Functionality. And I tried to change Button Bar Focus manually using the below code. I created a dialog box and tried to direct navigate in 3rd view.
```
RetrieveScreenFromItem(2)
gridConfig = GetButtonBarScreensConfig()["search"]
ShowNewScreenFromConfig(gridConfig)
```
Using this code changed the view successfully. But, not maintain a ButtonBar Focus(FootPrint). I Read the whole example and tried so many ways. But no luck. Is there any way to change a ButtonBar Focus(FootPrint).
![MoviesButtonBar](https://user-images.githubusercontent.com/39697799/81194059-d0ae9900-8fd9-11ea-83de-8a9876ece15c.jpg)

**Comment by RokuChris** [comment]
Focus and footprint are two different things. 

You can set the focused button the same way you do with other views, using the _jumpToItem_ field.

You cannot explicitly set which button has the footprint, but you can change how the footprint behaves using the _footprintStyle_ field.

**Comment by chaklasiyanikunj** [comment]
Thank you for your great response. 
I already try with below code. But, It's First Time Working perfectly. But, Secondtime It's not Work (It means using below code. First time nevigate and work like button bar using dialogbox. But, Second time It's show like below).
```
m.top.buttonBar.jumptoitem = 2
m.top.buttonBar.footprintStyle = "selection"
m.top.buttonBar.itemSelected = 3
RetrieveScreenFromItem(2)
gridConfig = GetButtonBarScreensConfig()["movies"]
ShowNewScreenFromConfig(gridConfig)
```
![series](https://user-images.githubusercontent.com/39697799/81571588-c74d7400-93bf-11ea-9687-1ee9ce8ef43b.jpg)

I tried below fields For deselection first field. But It doesn't work.
```
m.top.buttonBar.itemSelected = 1 and m.top.buttonBar.enableFootprint = false
```
Any other field is required for removing selecting the first field.

**Comment by RokuChris** [comment]
You should not be setting _itemSelected_. That is a read only field that you can observe to know which button the user selects, just like with other components. 

Also keep in mind that the "selection" footprint style will keep the footprint on the most recently selected button until the user selects something else. Using the "focus" footprint style will keep the footprint on the most recently focused button.

**Comment by chaklasiyanikunj** [comment]
Ok, Thank you. Now, I understand clearly.
