### ISSUE TITLE
In SGDex , Is it Possible to Change a Background in View Wise?

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#40]
Currently, By default, all views displayed grayscale background.

I need to change the background in view wise. I tried the below code. But no luck. Is there any field to change the background in view wise?
```
m.GridView.backgroundColor = "0x000000FF"
m.GridView.backgroundURI = "pkg:/images/background_image.png"
```
Using the below code It's Changed hole View Background.
```
m.top.backgroundColor = "0x000000FF"
m.top.backgroundURI = "pkg:/images/background_image.png"
```

**Comment by RokuChris** [comment]
Theming support is documented here: https://github.com/rokudev/SceneGraphDeveloperExtensions/blob/master/documentation/5-Themes_Guide.md

**Comment by chaklasiyanikunj** [comment]
I know about the theme. Using a theme, I was tried with other views like (TimeGrid View, Grid View). It's Working fine. Sorry, I forgot to mention. I tried with the Custom Grid Content Manager Example. But, not work with the Custom View. Is It Possible with the change background with the Custom View?

**Comment by RokuChris** [comment]
SGDEX themes do not work with custom views. You would need to handle that yourself in your view.

**Comment by chaklasiyanikunj** [comment]
Thanks for your answer I will try.
