### ISSUE TITLE
Is it possible to open an SGDEX View Inside another SGDEX View?

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#41]
I tried to open a Paragraph View or Search view inside a GridView. I tried with a dialog box. It open inside an SGDEX View using the below code. 
```
m.dlg = createObject("roSGNode", "Dialog")
m.port2 = createObject("roMessagePort")    
m.dlg.observeField("wasClosed", m.port2)
m.dlg.title = "Menu"
m.dlg.message = "ChannelIDPosterGrid OK Button"
m.dlg.buttons = ["OK"]
m.dlg.observeField("buttonSelected",m.port2)
m.dlg.getScene().dialog = m.dlg 
```

I refer to a ButtonBar Example. I tried to create a field and type node in the main scene using `m.top.grid = m.grid`. and Inside the other view.
```
m.dlg.getScene().getParent().visible = false
m.top.getScene().grid.visible = true
```
But no luck. Is there any solution to this.

**Comment by RokuChris** [comment]
I'm not sure I understand what you're trying to do. Opening a new view in response to the user selecting a button on a dialog is certainly possible. But I don't know what you mean by opening one view inside another.

SGDEX views are full screen elements managed on a stack by the ComponentController. There is documentation of that concept here: https://github.com/rokudev/SceneGraphDeveloperExtensions/blob/master/documentation/3-ViewStack_Guide.md

**Comment by chaklasiyanikunj** [comment]
I did this trick. But it just runs in the Main Scene. I want to open the grid view from inside the CustomZoomRowList(It's CustomGrid_ContentManager Example). I put in some code in CustomZoomRowList key event like below. It's Extends with the Group.
```
if key = "OK" then
    homeGrid = CreateObject("roSGNode", "GridView")
    content = CreateObject("roSGNode", "ContentNode")
    ' This tells the GridView where to go to fetch the content
    content.AddFields({
        HandlerConfigGrid: {
            name: "GridHandler"
        }
    })
    homeGrid.content = content
    m.top.ComponentController.callFunc("show", {
        view: homeGrid
    })
end if
```
But, It's giving an error. SGDEX View only managed with the show() in MainScene?

**Comment by RokuChris** [comment]
You can access the ComponentController from anywhere in the render thread context. Several of the sample channels do this. For example, the video preloading sample opens a VideoView in response to a button selection on a DetailsView: https://github.com/rokudev/SceneGraphDeveloperExtensions/blob/master/samples/video_preloading/components/DetailsView.brs

**Comment by chaklasiyanikunj** [comment]
Thank you for your reply. Now, I understand clearly.
