### ISSUE TITLE
Maintain Focus with SearchView gridNode(ZoomRowList)

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#46]
I referred to the SearchView Example and DetailView Example. Using the below Logic I opened a search view inside a DetailView.
```
sub OnSearchItemSelected(event as Object)
    ? "Item selected = " ; event.GetData()   
    m.item = event.GetData()   
    m.rawcontent = event.GetData() 
    m.details = ShowDetailsView(m.MoviesearchView.content.GetChild(m.rawcontent[0]), m.item[1])
end sub
```
Here, using this code I successfully opened Detail Screen, But, when I close the DetailView and jump to SearchView. it does not focus maintain with ZoomRowList. The same thing, I tried with GridView like the below same code. 
```
sub OnRowItemSelected(event as Object)
    m.grid = event.GetRoSGNode()
    m.itemSelected = event.GetData()
    m.customView.rowItemFocused : "m.customView.rowItemFocused
    m.rowContent = m.grid.content.GetChild(m.itemSelected[0])
    m.details = ShowDetailsView(m.rowContent, m.itemSelected[1])
end sub
```
Here, It's successfully handled automatically. It's not handled only with SearchView. Is there any way to handle Focus with SearchView when I opened another view? I successfully opened another view inside a search view. But, when I closed any view and back to SearchView Focus is not maintain. In SearchView initial focus set is keyboard.
I also tried with the observefieldscope field like 
```
if m.gridNode = invalid
    m.gridNode = m.layout.CreateChild(componentName)
    m.gridnode.ObserveFieldScoped("rowFocused", "OnFocusedChanged")
'    m.gridNode.ObserveFieldScoped("rowItemSelected", "OnRowItemSelected")
end if
sub OnFocusedChanged()
	 m.gridNode.setFocus(true)
end sub
'sub OnRowItemSelected()
'	 m.gridNode.setFocus(true)
'end sub
```
When I press the "back" key inside  DetailView. It shows only three lines like below in the console. I put a print statement in every function inside of SearchView. But, It's doesn't display.
```
SGDEX: View Manager runProcedure closeView
SGDEX: fire close for this View
SGDEX: Showing previous View
```
Is there any other way to handle this?

**Comment by RokuChris** [comment]
I'm not able to reproduce this. If I add a DetailsView to the SearchView sample using the `ShowDetailsView()` function from the DetailsView sample, focus works as expected and the item I selected on the SearchView regains focus when I close the DetailsView.

From the code you shared, it looks like you might be using a custom view. SGDEX will not manage focus within a custom view. If you are using a custom view, you may have to build some focus management logic for it.
