### ISSUE TITLE
Using SG Component (SearchView) Possible to observed gridview in MainScene?

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#48]
I checked the grid view in SearchView. It's a child of the layout. But, Is it possible to observe the grid view inside of the main scene like It's available or not? I checked both fields (rowItemFocused, rowItemSelected), It's displayed always. When the grid view is visible or not.

I print Searchview It's like below :

```
m.searchView : <Component: roSGNode:SearchView> =
{
    childRenderOrder: "last"
    clippingRect: <Component: roAssociativeArray>
    enableRenderTracking: false
    inheritParentOpacity: true
    inheritParentTransform: true
    muteAudioGuide: false
    opacity: 1
    renderPass: 0
    renderTracking: "disabled"
    rotation: 0
    scale: <Component: roArray>
    scaleRotateCenter: <Component: roArray>
    translation: <Component: roArray>
    visible: true
    change: <Component: roAssociativeArray>
    focusable: false
    focusedChild: <Component: roSGNode:Group>
    id: ""
    close: false
    content: <Component: roInvalid>
    errorCode: 0
    errorMsg: ""
    hintText: "Search here for moviename/releasedate"
    noResultsLabelText: "No results"
    overhang: <Component: roSGNode:Overhang>
    posterShape: "16x9"
    query: ""
    rowItemFocused: <Component: roArray>
    rowItemSelected: <Component: roArray>
    rowPosterShapes: <Component: roArray>
    saveState: false
    showNoResultsLabel: true
    showSpinner: false
    style: ""
    theme: <Component: roAssociativeArray>
    updateTheme: invalid
    viewContentGroup: <Component: roSGNode:Group>
    wasClosed: false
    wasShown: true
}
```

**Comment by RokuChris** [comment]
Views work the same whether they are at the top of the stack or not. The ComponentController manages the stack and you can always get the top view from it by doing something like this...

`m.top.ComponentController.currentView`

**Comment by chaklasiyanikunj** [comment]
Thank you for your Great reply. I used same line for displaying a current SGDex Component inside the MainScene. I'm trying to fetch the which component(keyboard or gridview) Focus is available in the search view component from inside Main Scene.

**Comment by RokuChris** [comment]
I see. That's not supported in the current version, but sounds like a useful feature. I will open a ticket to have it added.

**Comment by chaklasiyanikunj** [comment]
Thank you for the sharing the information.

**Comment by chaklasiyanikunj** [comment]
I'm not sure. that's way is good or not. But I made it. I created one extra field in Search View. and pass into the Search View Component. Now It's Working as Expected. Thank you for your help.
