### ISSUE TITLE
Is It possible to open a multiple row list in Sgdexview?

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/SceneGraphDeveloperExtensions#49]
I Created a Two Custom View. Both Views used the RowList. I created an alias for both views for rowitemfocused or rowitemselected field and used in the main scene. But, Here It's only able to access a single row list(CustomView) rowitemfocused or rowitemselected field. Which Custom View is launch in first. To maintain Both CustomViews Rowlist Fields in the main scene. Is it available on current versions? Or I should handle both fields in the custom views. But, I have doubt It will maintain focus in First Custom View when I press back from Second Custom View.

**Comment by RokuChris** [comment]
To work correctly with ContentManager, each custom view must have its own fields which are aliased to the respective fields on its own RowList. You should not share a single RowList between two custom views.

If things are set up correctly, you can use multiple custom views the same was you would use multiple SGDEX views.

**Comment by chaklasiyanikunj** [comment]
Thank you for your reply
