### ISSUE TITLE
CategoryListview does not appear to be working and complete

### ISSUE THREAD

**Issue by dctrotz** [rokudev/SceneGraphDeveloperExtensions#5]
The `CategoryListview` module has multiple issues. I have tried debugging it myself and it is a bit of a mess. It is such a shame too, since this could be the crux of many new channels on the Roku.  There are no examples of how to use this module. Please either fix or remove it from the SGDEX package.

**Comment by RokuChris** [comment]
The Episode Picker sample uses CategoryListView. It's working for me right now. If you have specific problems using it, we'd be happy to investigate further.

https://github.com/rokudev/SceneGraphDeveloperExtensions/tree/master/samples/7_EpisodePickerScreen
