### ISSUE TITLE
is still alive the project?

### ISSUE THREAD

**Issue by Allan-Nava** [rokudev/SceneGraphDeveloperExtensions#61]

**Comment by jduval23** [comment]
SGDEX is still currently supported. You can view highlights of the latest releases on the Roku Developer Blog: https://blog.roku.com/developer/search/sgdex

**Comment by Allan-Nava** [comment]
> SGDEX is still currently supported. You can view highlights of the latest releases on the Roku Developer Blog: https://blog.roku.com/developer/search/sgdex

Because I tried and it didn't works

**Comment by jduval23** [comment]
Did you follow the installation steps here: https://github.com/rokudev/SceneGraphDeveloperExtensions#Installation
