### ISSUE TITLE
TimeGrid sample build issues

### ISSUE THREAD

**Issue by ang128** [rokudev/SceneGraphDeveloperExtensions#82]
Hi, 
I tried to build the TimeGridView in the samples and I encountered some build errors. Have anyone encountered similar issue?
Thanks.

  Error: Undefined function `onIdleTimerChanged` in "onChange" attribute @1 components/SGDEX/ContentManager/ContentManagerTimeGrid/ContentManagerTimeGrid.xml
  Error: Undefined function `onControlChanged` in "onChange" attribute @1 components/SGDEX/ContentManager/ContentManagerTimeGrid/ContentManagerTimeGrid.xml
  Error: <field> must have "type" attribute @1 components/SGDEX/Views/MediaView/NowPlayingView/TrickPlayBar.xml
  Error: Undefined function `focusPercent` in "onChange" attribute @1 components/SGDEX/Views/OtherNodes/ItemComponents/RoundedRectangleItemComponent/RoundedRectangleItemComponent.xml
  Error: functions must declare return type @1,1 components/DeepLinkingLogic.brs
  Error: functions must declare return type @198,1 components/SGDEX/ButtonBar/ButtonBar.brs
  Error: functions must declare return type @448,1 components/SGDEX/ButtonBar/ButtonBar.brs
  Error: functions must declare return type @19,1 components/SGDEX/ComponentController/ComponentController.brs
  Error: functions must declare return type @41,1 components/SGDEX/ComponentController/ComponentController.brs
  Error: functions must declare return type @299,1 components/SGDEX/ContentManager/ContentManager.brs
  Error: functions must declare return type @482,28 components/SGDEX/ContentManager/ContentManager.brs
  Error: functions must declare return type @499,26 components/SGDEX/ContentManager/ContentManager.brs
  Error: `if` should not have empty `then` @667,32 components/SGDEX/ContentManager/ContentManager.brs
  Error: functions must declare return type @685,1 components/SGDEX/ContentManager/ContentManager.brs

**Comment by RokuChris** [comment]
Which sample are you having trouble with? The main TimeGridView sample is working as expected for me. 

https://github.com/rokudev/SceneGraphDeveloperExtensions/tree/master/samples/TimeGridView

**Comment by ang128** [comment]
Hi, 
I was trying the same TimrGridView
SceneGraphDeveloperExtensions/samples/TimeGridView

Thanks,

**Comment by ang128** [comment]
Do you mind providing the makefile? I suspect it is the makefile causing the issue. Thanks.

**Comment by ang128** [comment]
yes. the issue is fixed. thanks.
