### ISSUE TITLE
How to set theme settings?

### ISSUE THREAD

**Issue by RomanSkrypnyk-main** [rokudev/SceneGraphDeveloperExtensions#93]
`sub Show(args as Object)
    ShowHomeScreen() 
end sub`

`function ShowHomeScreen() as Object`
    `m.grid = CreateObject("roSGNode", "GridView") `
     
**`m.grid.theme = { `
         `backgroundColor: "FFFFFFFF" `
    ` }`**

`m.grid.SetFields({ `
         `style: "hero" `
         `posterShape: "16x9" `
     ` }) `
     `content = CreateObject("roSGNode", "ContentNode") `
     `content.AddFields({ `
         `HandlerConfigGrid: { `
             `name: "HomeCH" `
         `} `
     `}) `
     `m.grid.content = content `
     `m.grid.ObserveField("rowItemSelected", "OnGridItemSelected") `
     `m.top.ComponentController.CallFunc("show", { `
         `view: m.grid `
     `}) `
     `return m.grid `
 `end function`

**Comment by RokuChris** [comment]
Colors must be specified in hex, the same as in RSG... "0x8000FFFF"

**Comment by RomanSkrypnyk-main** [comment]
thank you. Now I will know.
it would be very helpful to add this information to 5-Themes_Guide.md
